version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dummy-app
      - POSTGRES_USER=dummy-app
      - POSTGRES_DB=dummy-app
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - the_bridge

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: dummy-app
      KC_DB_USERNAME: dummy-app
      KC_DB_PASSWORD: dummy-app
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - the_bridge

networks:
  the_bridge:
    driver: bridge

volumes:
  postgres_data:
    driver: local