server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dummy-app
    driver-class-name: org.postgresql.Driver
    username: dummy-app
    password: dummy-app

  jpa:
    # JPA / HIBERNATE
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

