version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dummy-app
      - POSTGRES_USER=dummy-app
      - POSTGRES_DB=dummy-app
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - the_bridge

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev --http-port 8080 --import-realm
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
      - ./keycloak/health-check.sh:/opt/keycloak/health-check.sh
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: dummy-app
      KC_DB_USERNAME: dummy-app
      KC_DB_PASSWORD: dummy-app
      KC_DB_SCHEMA: public
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 10s
      retries: 12
    networks:
      - the_bridge

#  dirty-blog:
#    container_name: dirty-blog
#    image: dirty-blog:0.0.1-SNAPSHOT
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dummy-app
#      - SPRING_DATASOURCE_USERNAME=dummy-app
#      - SPRING_DATASOURCE_PASSWORD=dummy-app
#       Spring Security OAuth2 Configuration
#      - SERVER_PORT=8081
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://127.0.0.1:8080/realms/dirty-blog
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://127.0.0.1:8080/realms/dirty-blog/protocol/openid-connect/certs
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE=authorization_code
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID=dirty-blog-rest-api
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_PROVIDER=keycloak
#      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE=openid,profile,email
#      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://127.0.0.1:8080/realms/dirty-blog
#      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USERNAME_ATTRIBUTE=preferred_username
#      - JWT_AUTH_CONVERTER_APPLICATION_ID=dirty-blog-rest-api
#      - JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE=preferred_username
#    depends_on:
#      postgres:
#        condition: service_healthy
#      keycloak:
#        condition: service_healthy
#    networks:
#      - the_bridge

networks:
  the_bridge:
    driver: bridge

volumes:
  postgres_data:
    driver: local